dataset:
    # root_path: '/Users/hannahschieber/GitHub/deep_seg/data/Simpsons/simpsons_dataset/'
    root_path: '/Users/hannahschieber/GitHub/deep_seg/data/PennFudanPed'
    image_sub_path: 'PNGImages'
    mask_sub_path: 'PedMasks'
    number_of_classes: 2

learning_process:
    learning_rate: 0.001
    weight_decay: 0
    num_workers: 0
    ignore_index: 255

logging:
    output_dir ''
